"""Add job_title to Application

Revision ID: 4ef3c6edf23f
Revises: af4868a91aff
Create Date: 2025-05-29 16:37:57.545755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef3c6edf23f'
down_revision = 'af4868a91aff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('job_title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'job_title')
    # ### end Alembic commands ###
