"""change first name and last name to full name

Revision ID: af4868a91aff
Revises: 9d01532f5a67
Create Date: 2025-05-28 10:16:14.701342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af4868a91aff'
down_revision = '9d01532f5a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('full_name', sa.String(length=100), nullable=False))
    op.add_column('application', sa.Column('employer_contact', sa.String(length=20), nullable=False))
    op.add_column('application', sa.Column('employment_duration', sa.String(length=50), nullable=False))
    op.drop_column('application', 'first_name')
    op.drop_column('application', 'job_title')
    op.drop_column('application', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('last_name', sa.VARCHAR(length=50), nullable=False))
    op.add_column('application', sa.Column('job_title', sa.VARCHAR(length=100), nullable=True))
    op.add_column('application', sa.Column('first_name', sa.VARCHAR(length=50), nullable=False))
    op.drop_column('application', 'employment_duration')
    op.drop_column('application', 'employer_contact')
    op.drop_column('application', 'full_name')
    # ### end Alembic commands ###
