"""Convert document fields to JSON format

Revision ID: d78a82d6b74b
Revises: 8e835789384f
Create Date: 2025-10-04 20:17:24.083881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd78a82d6b74b'
down_revision = '8e835789384f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('payslips_path', sa.Text(), nullable=True))
    op.add_column('application', sa.Column('bank_statements_path', sa.Text(), nullable=True))
    op.drop_column('application', 'payslip_path')
    op.drop_column('application', 'bank_statement_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('bank_statement_path', sa.VARCHAR(length=200), nullable=True))
    op.add_column('application', sa.Column('payslip_path', sa.VARCHAR(length=200), nullable=True))
    op.drop_column('application', 'bank_statements_path')
    op.drop_column('application', 'payslips_path')
    # ### end Alembic commands ###
