"""Add detailed address fields (nullable)

Revision ID: e4057d8ed4f2
Revises: 4ef3c6edf23f
Create Date: 2025-10-03 10:54:47.277935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4057d8ed4f2'
down_revision = '4ef3c6edf23f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('address_line1', sa.String(length=100), nullable=True))
    op.add_column('application', sa.Column('address_line2', sa.String(length=100), nullable=True))
    op.add_column('application', sa.Column('suburb', sa.String(length=50), nullable=True))
    op.add_column('application', sa.Column('city', sa.String(length=50), nullable=True))
    op.add_column('application', sa.Column('postal_code', sa.String(length=10), nullable=True))
    op.add_column('application', sa.Column('country', sa.String(length=50), nullable=True))
    op.drop_column('application', 'address')
    op.add_column('transaction', sa.Column('description', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('address_line1', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('address_line2', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('suburb', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('postal_code', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('country', sa.String(length=50), nullable=True))
    op.drop_column('user', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('user', 'country')
    op.drop_column('user', 'postal_code')
    op.drop_column('user', 'city')
    op.drop_column('user', 'suburb')
    op.drop_column('user', 'address_line2')
    op.drop_column('user', 'address_line1')
    op.drop_column('transaction', 'description')
    op.add_column('application', sa.Column('address', sa.VARCHAR(length=200), nullable=False))
    op.drop_column('application', 'country')
    op.drop_column('application', 'postal_code')
    op.drop_column('application', 'city')
    op.drop_column('application', 'suburb')
    op.drop_column('application', 'address_line2')
    op.drop_column('application', 'address_line1')
    # ### end Alembic commands ###
