"""Add balance fields to user model

Revision ID: f2b4f01a8a12
Revises: 
Create Date: 2025-05-18 20:16:52.235469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2b4f01a8a12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('total_balance', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('amount_due', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('due_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'due_date')
    op.drop_column('user', 'amount_due')
    op.drop_column('user', 'total_balance')
    # ### end Alembic commands ###
